apiVersion: v1
kind: Service
metadata:
  name: sample-inference
  labels:
    app.kubernetes.io/name: sample-inference
spec:
  selector:
    app.kubernetes.io/name: sample-inference
  ports:
    - name: http
      port: 80
      targetPort: http
