name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Kubernetes validation
        run: |
          echo "Running kubeconform..."
          # kubeconform ./k8s

      - name: Security scan (Trivy)
        run: |
          echo "Running Trivy scan..."
          # trivy fs .

      - name: Generate SBOM (Syft)
        run: |
          echo "Generating SBOM..."
          # syft . -o table
